server:
  port: 8000
spring:
  application:
    name: stock-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
  datasource:
    url: jdbc:mysql://localhost:3306/time_hx_1223?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
