server:
  port: 8000
spring:
  application:
    name: stock-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
  datasource:
    url: jdbc:mysql://localhost:3306/time_hx_1223?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456ok**
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  mybatis-plus:
    type-aliases-package: com.lyc.test.model
    type-aliases-super-type: java.lang.Object
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazy-loading-enabled: true
      multiple-result-sets-enabled: true
      use-generated-keys: true
      default-statement-timeout: 60
      default-fetch-size: 100
    mapper-locations: classpath*:mapper/*.xml
rocketmq:  #rocketmq 默认分配的jvm内存较大，要注意，如果启动失败可能是内存太大，可以改小一点
  name-server: localhost:9876
  producer:
    group: group-test-stock
